version: "3.9"
services:
  mysql:
    image: mariadb:10.11.4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=aisu
      - MYSQL_ROOT_PASSWORD=4ab4008b362142c391cc9e1ab98addc6b25f00f5
      - MYSQL_USER=aisu
      - MYSQL_PASSWORD=4ab4008b362142c391cc9e1ab98addc6b25f00f5
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./oas3/:/oas3
    environment:
      SWAGGER_JSON: /oas3/openapi.yaml
volumes:
  mysql_data:
  redis_data:
