version: "3.9"
services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aisu
      - POSTGRES_USER=aisu
      - POSTGRES_PASSWORD=4ab4008b362142c391cc9e1ab98addc6b25f00f5
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./oas3/:/oas3
    environment:
      SWAGGER_JSON: /oas3/openapi.yaml
volumes:
  postgres_data:
  redis_data:
